// 참가자 온보딩 진행률 계산 — 서버/클라이언트 공용.
//
// 수집 대상:
//  1) 보호자 이름 (자동생성 "학부모_XXXX" 가 아니면 완료)
//  2) 각 자녀의 생년월일 + 성별

export type OnboardingStep = {
  key: string;
  label: string;
  done: boolean;
};

export type OnboardingProgress = {
  steps: OnboardingStep[];
  doneCount: number;
  totalCount: number;
  percent: number;
  allDone: boolean;
};

type UserLike = { parent_name: string | null };
type ChildLike = {
  id: string;
  name: string;
  birth_date: string | null;
  gender: "M" | "F" | null;
};

const AUTO_PARENT_NAME_RE = /^학부모_\d{3,4}$/;

export function isAutoGeneratedParentName(raw: string | null): boolean {
  if (!raw) return true;
  return AUTO_PARENT_NAME_RE.test(raw.trim());
}

export function computeOnboardingProgress(
  _user: UserLike,
  children: ChildLike[]
): OnboardingProgress {
  const steps: OnboardingStep[] = [];

  // 자녀별 생년월일 + 성별
  for (const c of children) {
    steps.push({
      key: `child-${c.id}`,
      label: `${c.name || "아이"} 정보`,
      done: !!c.birth_date && !!c.gender,
    });
  }

  const doneCount = steps.filter((s) => s.done).length;
  const totalCount = steps.length;
  const percent =
    totalCount === 0 ? 100 : Math.round((doneCount / totalCount) * 100);
  const allDone = totalCount > 0 && doneCount === totalCount;

  return { steps, doneCount, totalCount, percent, allDone };
}
