// 미션 사진 나눠보기 — 순수 로직 (서버/클라이언트 공용, DB 접근 없음).
//
// 아이 얼굴을 남에게 보이는 일이라 판단 규칙을 한 곳에 모은다. 화면과 서버가
// 같은 함수를 쓰지 않으면 "안내는 떠 있는데 실제로는 안 보이는" 정도로 끝나지
// 않고, **공개돼선 안 될 사진이 새 나가는** 종류의 사고가 된다.
//
// 공개 판단은 기관 한 곳에서 한다. 두 조건이 맞아야 한 장이 피드에 오른다:
//   1) 기관이 이 행사에서 사진 나눠보기를 켰다
//   2) 기관이 이미 확인한 사진이다(자동승인 포함) — 검토 중·반려는 절대 안 된다
//
// 보호자별 개별 동의 토글은 두지 않는다. 켤 사람은 안 켜고, 안 켠 사람은 자기
// 사진이 왜 안 보이는지 모른 채 끝나 피드가 텅 빈 채로 남았다. 대신 기관이
// 켜는 순간이 곧 "이 행사는 사진을 나눠본다" 는 선언이고, 참가자 화면에는
// 지금 이 사진이 남에게 보이는지를 항상 문장으로 적어 둔다.

import { isAutoGeneratedParentName } from "@/lib/app-user/onboarding";

/** 피드에 올릴 수 있는 상태. 검토 중(SUBMITTED/PENDING_REVIEW)·반려는 제외. */
const VISIBLE_STATUSES = new Set(["AUTO_APPROVED", "APPROVED"]);

/** 한 미션에서 한 사람이 누를 수 있는 좋아요 수. */
export const LIKES_PER_MISSION = 3;
/** 한 사진이 좋아요로 받을 수 있는 도토리 상한. */
export const LIKE_ACORN_CAP = 5;

export type PhotoVisibility =
  | { visible: true }
  | { visible: false; reason: string };

/** 참가자 화면에 적어줄 안내 한 줄. 기관이 안 켠 행사면 아무 줄도 띄우지 않는다. */
export type AutoShareNotice =
  | { state: "live"; text: string }
  | { state: "waiting"; text: string }
  | null;

/**
 * 이 제출물이 지금 피드에 오를 수 있는가.
 *
 * 조회에서 이미 걸러 오더라도 렌더 직전에 한 번 더 통과시킨다 — 필터를 한
 * 군데서만 지키면, 나중에 조회를 고치는 사람이 그 조건을 빠뜨렸을 때 아무도
 * 모르게 사진이 노출된다.
 */
export function resolvePhotoVisibility(args: {
  feedEnabled: boolean;
  status: string;
}): PhotoVisibility {
  if (!args.feedEnabled) {
    return { visible: false, reason: "기관이 사진 나눠보기를 켜지 않았어요" };
  }
  if (!VISIBLE_STATUSES.has(args.status)) {
    return { visible: false, reason: "아직 기관이 확인하지 않은 사진이에요" };
  }
  return { visible: true };
}

/**
 * 이 사진이 지금 다른 가족에게 보이는지를 참가자에게 알려줄 문장.
 *
 * 고를 수 없다고 해서 말해주지 않아도 되는 건 아니다 — 오히려 선택지가 없을수록
 * "지금 이게 남에게 보이는 상태인가" 는 항상 화면에 적혀 있어야 한다.
 *
 * @param status 제출 후 상태. 아직 제출 전(찍는 화면)이면 생략 — "기관 확인이
 *   끝나면" 쪽 문장이 나간다.
 */
export function describeAutoShare(args: {
  feedEnabled: boolean;
  status?: string | null;
}): AutoShareNotice {
  if (!args.feedEnabled) return null;
  const live = args.status != null && VISIBLE_STATUSES.has(args.status);
  return live
    ? {
        state: "live",
        text: "이 행사에 참가한 가족들이 사진 피드에서 볼 수 있어요.",
      }
    : {
        state: "waiting",
        text: "기관 확인이 끝나면 이 행사에 참가한 가족들이 볼 수 있어요.",
      };
}

export type LikeGate =
  | { canLike: true }
  | { canLike: false; reason: string };

/**
 * 이 사진에 좋아요를 누를 수 있는가.
 *
 * 서버 액션과 화면이 같은 함수를 본다. 화면이 버튼을 감추는 것만 믿으면, 눌린
 * 순간 서버가 조용히 거절해 "눌렀는데 아무 일도 안 일어나는" 화면이 된다.
 *
 * 이미 누른 사진은 언제나 canLike — 취소해야 하니까. 남은 개수는 취소로 돌아온다.
 */
export function resolveLikeGate(args: {
  feedEnabled: boolean;
  status: string;
  /** 이 사진이 내 것인가. */
  isMine: boolean;
  /** 내가 이미 이 사진에 눌렀는가. */
  alreadyLiked: boolean;
  /** 이 미션에서 내가 이미 쓴 좋아요 수. */
  usedInMission: number;
}): LikeGate {
  if (args.alreadyLiked) return { canLike: true };
  if (!args.feedEnabled) {
    return { canLike: false, reason: "이 행사는 사진 나눠보기를 쓰지 않아요" };
  }
  if (args.isMine) {
    return { canLike: false, reason: "내 사진에는 누를 수 없어요" };
  }
  if (!VISIBLE_STATUSES.has(args.status)) {
    return { canLike: false, reason: "아직 기관이 확인하지 않은 사진이에요" };
  }
  if (args.usedInMission >= LIKES_PER_MISSION) {
    return {
      canLike: false,
      reason: `이 미션의 좋아요를 다 썼어요 (${LIKES_PER_MISSION}개)`,
    };
  }
  return { canLike: true };
}

/**
 * 이 사진 주인이 지금 받아야 할 도토리와, 그러려면 원장에 적을 차액.
 *
 * 좋아요마다 1개씩 주지 않고 매번 다시 계산하는 이유: 취소가 가능한데 상한이
 * 있으면 "취소된 그 좋아요가 도토리를 준 좋아요였나" 를 판정할 수 없다. 총량만
 * 맞추면 그 질문 자체가 사라진다.
 *
 * 상한을 넘은 구간(좋아요 6번째부터)에서는 눌러도 취소해도 delta 가 0이다 —
 * 하트 숫자는 계속 올라가지만 도토리는 5에서 멈춘다.
 *
 * @param granted 이 사진으로 지금까지 오간 도토리 합계(원장 기준, 취소분 반영).
 */
export function resolveLikeGrant(args: {
  likeCount: number;
  granted: number;
  cap?: number;
}): { target: number; delta: number } {
  const cap = args.cap ?? LIKE_ACORN_CAP;
  const target = Math.max(0, Math.min(cap, args.likeCount));
  return { target, delta: target - args.granted };
}

/**
 * "3분 전" — 피드 캡션용 상대 시각.
 *
 * @param nowMs 기준 시각. 렌더 중 Date.now() 를 부르면 react-hooks/purity 에
 *   걸리고 SSR/CSR 결과가 어긋난다. 호출부가 직접 부르지 않게 기본값을 여기서
 *   만든다(resolveApplicationGate 와 같은 규약).
 */
export function formatRelativeTime(
  iso: string | null | undefined,
  nowMs?: number
): string {
  if (!iso) return "";
  const ms = new Date(iso).getTime();
  if (!Number.isFinite(ms)) return "";

  const diffSec = Math.floor(((nowMs ?? Date.now()) - ms) / 1000);
  if (diffSec < 0) return "방금";
  if (diffSec < 60) return "방금";
  if (diffSec < 3600) return `${Math.floor(diffSec / 60)}분 전`;
  if (diffSec < 86400) return `${Math.floor(diffSec / 3600)}시간 전`;
  const days = Math.floor(diffSec / 86400);
  if (days < 7) return `${days}일 전`;
  return `${Math.floor(days / 7)}주 전`;
}

/**
 * 피드 캡션에 걸 가족 이름 — "햇살반 홍길동"(→ "햇살반 홍길동 가족").
 *
 * 보호자 이름을 앞세우지 않는 이유: 기관이 명단으로 대량 등록한 계정은 이름이
 * "학부모_0914" 같은 자동 생성값이다. 그대로 걸면 피드가 번호표 목록처럼 보이고,
 * 정작 그 자리에서 서로를 부르는 이름(아이 이름)은 어디에도 안 나온다.
 * 관제실 사진 월(control-room/queries.ts)이 이미 같은 이유로 원생 이름을 앞세운다.
 *
 * 반 이름을 앞에 붙이는 이유: 같은 행사에 이름이 겹치는 아이가 있고, 부모들은
 * 서로를 "몇 반 누구 엄마" 로 안다. 반이 비어 있는 아이도 많아 **있을 때만** 붙인다.
 *
 * 형제자매는 "·" 로 잇는다(관제실과 같은 표기). 셋 이상이어도 그대로 잇고
 * 화면에서 잘라 쓴다 — 캡션 한 줄에 다 안 들어가는 건 화면 사정이다.
 */
export function formatFamilyName(args: {
  childNames?: string[] | null;
  /** 반 이름. 비어 있으면 접두 없이 이름만 나간다. */
  className?: string | null;
  parentName?: string | null;
}): string {
  const cls = (args.className ?? "").trim();
  const withClass = (name: string) => (cls ? `${cls} ${name}` : name);

  const kids = (args.childNames ?? [])
    .map((n) => (n ?? "").trim())
    .filter(Boolean);
  if (kids.length > 0) return withClass(kids.join("·"));

  // 아이 이름이 없을 때만 보호자 이름. 자동 생성 이름이면 차라리 비운다 —
  // "학부모_0914 가족" 은 알려주는 게 없고 계정 번호만 흘린다.
  const parent = (args.parentName ?? "").trim();
  if (!parent || isAutoGeneratedParentName(parent)) return "";
  return withClass(parent);
}

/** "홍길동 가족 · 3분 전" — 이름이 없으면 시각만. */
export function formatFeedMeta(
  name: string | null | undefined,
  submittedAt: string | null | undefined,
  nowMs?: number
): string {
  const who = (name ?? "").trim();
  const when = formatRelativeTime(submittedAt, nowMs);
  if (who && when) return `${who} 가족 · ${when}`;
  if (who) return `${who} 가족`;
  return when;
}
